#!/usr/bin/env bash
# scripts/install.sh — 把生成的 llmw wrapper 装进 ~/.local/bin（Phase 2）
set -euo pipefail

usage() {
  cat <<'USG'
usage: ./scripts/install.sh
  生成 ~/.local/bin/llmw（PYTHONPATH 指向本仓库），并按需注册 PATH。
  卸载用 ./scripts/uninstall.sh。
USG
}

# 脚本在 scripts/，仓库根是其上一级；不依赖 readlink -f（兼容 macOS bash 3.2）
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
bin_dir="$HOME/.local/bin"

mkdir -p "$bin_dir"

cat > "$bin_dir/llmw" <<EOF
#!/usr/bin/env bash
# llmw launcher — generated by install.sh. Repo: $repo_root
# 仓库被挪走会失效；重跑 ./scripts/install.sh 即可修复。
export PYTHONPATH="$repo_root:\$PYTHONPATH"
exec python3 -m llmw "\$@"
EOF
chmod +x "$bin_dir/llmw"

echo "已安装 llmw -> $bin_dir/llmw"
